version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - measurements
  measurements:
    build: ./measurements
    environment:
      - DATABASE_USERNAME=parachute
      - DATABASE_PASSWORD=hereforbeer
      - FLASK_APP=index.py
    volumes:
      - ./measurements:/usr/src/app
    depends_on:
      - db
    restart: on-failure
  db:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=parachute
      - MONGO_INITDB_ROOT_PASSWORD=hereforbeer
    ports:
      - "27017:27017"
