version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - measurements
      - events
      - db
      - influxdb
  measurements:
    build: ./measurements
    environment:
      - DATABASE_HOST=influxdb
      - DATABASE_PORT=8086
    volumes:
      - ./measurements:/usr/src/app
    ports:
      - "5000"
    depends_on:
      - influxdb
      - db
    restart: on-failure
  events:
    build: ./events
    environment:
      - DATABASE_HOST=influxdb
      - DATABASE_PORT=8086
    volumes:
      - ./events:/usr/src/app
    ports:
      - "5000"
    depends_on:
      - influxdb
      - db
    restart: on-failure
  db:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=parachute
      - MONGO_INITDB_ROOT_PASSWORD=hereforbeer
    ports:
      - "27017:27017"
  influxdb:
    image: influxdb
    environment: 
      - INFLUXDB_DB=water
      - INFLUXDB_ADMIN_USER=parachute
      - INFLUXDB_ADMIN_PASSWORD=hereforbeer
      - INFLUXDB_USER=red
      - INFLUXDB_USER_PASSWORD=nodered
      - INFLUXDB_ADMIN_ENABLED=true
    ports:
      - "8086"
  chronograf:
    image: chronograf:latest
    entrypoint: 'chronograf --influxdb-url=http://influxdb:8086'
    ports:
      - "8888"
    
